-- ? COMMON TABLES -----------------------------------------------------------------------------------------------------

-- Table: general_user (Common table for all systems)
-- todo: Add additional fields as needed for each system
-- todo: Add some constrains for email & role...
DROP TABLE IF EXISTS auth.general_user CASCADE;
CREATE TABLE IF NOT EXISTS auth.general_user (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    additional_info JSONB
);

-- Table: auth_user (Common table for all systems)
DROP TABLE IF EXISTS auth.auth_user CASCADE;
CREATE TABLE IF NOT EXISTS auth.auth_user (
    id INTEGER NOT NULL REFERENCES auth.general_user(id) ON DELETE CASCADE,
--     email_hash VARCHAR(255) NOT NULL,
--     password VARCHAR(255) NOT NULL
--     This hash is generated by the system using the SHA-256 algorithm
--     The hash contains the email and password & the system should be able to decrypt it to get the email and password!
    password_hash VARCHAR(255) NOT NULL
);
